### ISSUE TITLE
out of sync with root repo?

### ISSUE THREAD

**Issue by AndrewAnnex** [conda-forge/ale-feedstock#40]
### Comment:

@jessemapel  I see that 0.8.7 was just released on the main repo but the latest release on this feedstock is also 0.8.7 but it was released months ago? Maybe something todo with the scrubbing? I noticed the isd_generate script was missing when I tried installing it

**Comment by jessemapel** [comment]
All of the stuff on the root repo has gotten kind of topsy-tervy due to the history scrubbing work. This is up to date with 0.8.7, we haven't tagged the next release yet (likely 0.9); that will contain the ISD generation script.

I'm in the final steps of the release processes to get that version out the door.
